name: PHPUnit Tests
on:
  push:
    branches:
      - main
      - develop
      - feature/GP-182
  pull_request:

jobs:
  test-php:
    name: ${{ matrix.php_versions }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php_versions: [ '8.0', '7.4', '7.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          coverage: xdebug

      - name: Composer Install
        run: composer install --optimize-autoloader --prefer-dist

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Log debug information
        run: |
          npm --version
          node --version
          git --version
          php --version
          composer --version

      - name: Running PHPUnit Tests
        run: |
          php --version
          npm i -g @wordpress/env
          npm run test:unit:php
          echo "CONTAINERS"
          echo $(docker container ls)
          docker cp $(docker ps -aqf "name=tests-wordpress"):$(docker exec $(docker ps -aqf "name=tests-wordpress") pwd)/coverage.xml coverage.xml
        if: ${{ success() || failure() }}

      - name: Fix Code Coverage Paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
